server:
  port: 8020


spring:
  thymeleaf:
    cache: false

  h2:
    console:
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:sb_dev;MODE=MySQL
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

  security:
    user:
      name: user
      password: 123456